### ISSUE TITLE
[Server] As a developer, I should be able to insert custom code via configuration in order to introduce custom functionality.

### ISSUE THREAD

**Issue by luke-siedle** [gernzy/gernzy#87]
We need to have a design that allows for third party developers, including ourselves, to extend the features of the app in different places. In the WordPress / Woocommerce world, you use the `add_filter` and `add_action` methods, the first being to modify values, the second being to trigger behaviour on certain actions, like event listeners. 

I don't like this architecture because you never know what's subscribed to events. There could be hundreds of plugins listening to an event which could block or break a PHP script from completing, and you'd have to dig through a lot of error logging to try to track this down.  

It would be good to expose all actions that listen to a particular event in configuration, for example, let's say that Stripe needed two actions to be configured:
```
<?php
   
   use Gernzy\Listeners\BeforeCheckout;
   use Gernzy\Listeners\AfterCheckout; 
   use ThirdParty\Stripe\Actions\StripeBeforeCheckout;
   
   return [
     // Add listeners to the beforecheckout event
     BeforeCheckout::class => [
        StripeBeforeCheckout::class
     ],
     AfterCheckout::class => [
       StripeAfterCheckout::class
     ]
   ];
```
So I'm picturing a contract in Laravel that must implement some methods. The actions will be performed in a chain. 

```
<?php
      use Gernzy\Contracts\ActionContract;
      use Gernzy\Classes\ActionClass;
      namespace ThirdParty\Stripe\Actions;

      
      class StripeBeforeCheckout implements ActionContract {
         public function __construct ...

         public function run( ActionClass $action  ) : ActionClass {
             $data = $action->getOriginalData();
             $mod = $action->getModifiedData();
             $action->eventPreventDefault();
             return $action;
         }
      }
```

There are quite a few parts when you look at this:
- A Gernzy contract (an interface that must always implement xyz methods). 
- An action object which should also implement certain methods
- The third party class which will be able to access the action's historical data. There's a run method as an example here, but the actual methods involved would be TBC and evolve as we build out the third party packages. 

Wherever the actual checkout is taking place in Laravel code, this "event" needs to be triggered. It would then set off the chain of whatever has subscribed to it from configuration. 

In Laravel there are events so we could look at combining this implementation with events, however this could become dirty if third party developers starting subscribing to events without going through our contracts and configuration. If this is possible with events I'd prefer to have our own internal events system. So for example, in a checkout method somewhere in Laravel we could have the following:

```
   use Gernzy\Services\EventService;
   use Gernzy\Listeners\BeforeCheckout;
   
   // Before checkout
   $action = EventService::triggerEvent( BeforeCheckout::class );

    ...

   // After checkout 
   $action = EventService::triggerEvent( AfterCheckout::class );
```

This would set off the chain of actions that have subscribed. We should consider how the data returned by the actions are used. Because there's an infinite number of possibilities, we may not use this data at all, apart from possibly "preventing" the default behaviour, using a method like eventPreventDefault() similar to what jQuery has.

**Comment by AlexeiaW** [comment]
So just thinking about this now. When you trigger the event, you will loop through whatever classes have subscribed to this. When you loop through, you will want to pass an object through each one that stores the action history, allowing you to attach a bit of data if you want to each iteration.
I think what we would have in my example, would be starting off with an empty action object, and as it passes through it can store useful meta data. So the ActionClass would be a new object, maybe implementing a very simple contract which sets / gets data. That contract might also evolve a bit.
To give you an example, we could have 2 plugins subscribing to afterCheckout. The first might generate a coupon code or something like that, and bind it to the action object. The second plugin would receive the action and be able to read that data in if it wanted to make use of it. So it lets multiple plugins talk to each other in order of their subscription.

So I think we do need to use the container, so that we can inject services easily in the constructor. So the container would be making the `StripeAfterCheckout::class` to allow for that.

Okay from the event service you'll be running that event called StripeBeforeCheckout, something like
```
$action = new Action();
foreach( $eventRegister as $event ){
  $eventClass = App::make( $event );
  $eventInstance = new $eventClass();
  $action = $eventInstance->run( $action );
}
```

I can't really visualise what the action will consist of but maybe just some basic methods of storing data on it. A way to share information from one event to the next

We may have a default event defined on beforeCheckout for example, and be able to prevent this from happening. In which case it would be something like
```
$action = new Action();
foreach( $eventRegister as $event ){
  $eventClass = App::make( $event );
  $eventInstance = new $eventClass();
  $action = $eventInstance->run( $action );
}
if( ! $action->preventDefault() ){
   // Do some default behaviour, e.g. redirecting to thank you page
} else {
   // Nothing happens
}
```

o just to clarify, we start off with an empty action class, which will morph as it runs through various events. We'd probably want to stipulate some kind of data structure on it.
Maybe the set and get methods can specify the class name where it came from like
```
public function setMeta( $data ){
   $this->meta[ $classNameOfEvent ] = $data
}
```
I just don't know how we'll get the class name but let's wait and see how the structure comes out
10:27
Thinking about this now, we'll probably be passing in some initial useful data, lets say beforeCheckout passes the cart object in the meta data.
```
$action = new Action( [
  'cart' => $cart
]);
```

obviously it gets pretty limitless so we have to think carefully about this too. let's just take it a step at a time and think about all the possible usage
